### PR TITLE
Bullet Span

### PR DESCRIPTION
**Pull request by raghunandankavi2010**
Added Bullet Span

### CODE REVIEW

**Comment by raghunandankavi2010** [comment]
Added text fade  in option. We need to option of adding spans to text based on regex. Its hard to always remember index.

**Comment by AdamMc331** [comment]
What is the difference between this and #12 ?

**Comment by raghunandankavi2010** [comment]
I guess that's a wrong pr. Check this.

**Comment by AdamMc331** [comment]
Sounds good. If no issues I'll end up merging this manually since there are conflicts, and will keep you updated. Going to go over and close the other PR.

**Comment by raghunandankavi2010** [comment]
Cool.

**Comment by AdamMc331** [comment]
Resolved conflicts, going to merge in and will retest once merged to make sure everything is still good. Thanks!

**Comment by AdamMc331** [comment]
@raghunandankavi2010 Version 1.0.4 is live.

**Comment by raghunandankavi2010** [comment]
nice. i also see that you converted class files to kotlin.

**Pull request merged**
