### PR TITLE
Added NumberSpan

### PR DESCRIPTION
**Pull request by raghunandankavi2010**
This is just my first attempt to adding Number Span. I am sure this can be further enhanced like adding NumberSpan to the lines based on user choice.

### CODE REVIEW

**Comment by raghunandankavi2010** [comment]
screenshot_20160813-121851

Point 5 does not look good . I am looking at a way to fix this.

**Comment by AdamMc331** [comment]
Thanks! I will test this out this weekend. Please let me know if you find a fix to number 5.

**Comment by raghunandankavi2010** [comment]
The problem is here in NumberSpan

```
 @Override
 public void drawLeadingMargin(Canvas c, Paint p, int x, int dir, int top, int baseline, int bottom,
                              CharSequence text, int start, int end, boolean first, Layout l) {

    Spanned spanned = (Spanned) text;
    if (!mIgnoreSpan && spanned.getSpanStart(this) == start) {
        // set paint
        Paint.Style oldStyle = p.getStyle();
        float oldTextSize = p.getTextSize();
        p.setStyle(Paint.Style.FILL);
        mTextSize = baseline - top;
        p.setTextSize(mTextSize); // the text size changes for superscript based on base line  and top
```

This can be fixed by adding a text size and using the same in Number Span.

**Comment by raghunandankavi2010** [comment]
Clearing numberspan is not working. Working on it.

**Comment by raghunandankavi2010** [comment]
Is this tested yet?

**Comment by AdamMc331** [comment]
Testing this now. Sorry to have taken so long.

**Comment by AdamMc331** [comment]
Looks good! Will merge and prepare an update soon.

**Pull request merged**
